#!/usr/bin/env node
/**
 * Deterministic JSON Schema emission for the published protocol surface.
 *
 * Determinism is a hard requirement, not a nicety: the drift check compares
 * bytes, and a generator whose output depends on key insertion order or on a
 * timestamp would make `pnpm schema:check` flap. So every object is emitted
 * with sorted keys and there is nothing environment-dependent in the output.
 *
 * Two artefacts are produced from one source:
 *   packages/protocol/schemas/<name>.json      for non-TypeScript consumers
 *   packages/protocol/src/generated/json-schemas.ts   for the `/schemas` subpath
 *
 * Usage: node tools/repo/generate-schemas.ts [--check]
 */

import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';

import { PUBLISHED_SCHEMAS, PUBLISHED_SCHEMA_NAMES } from '../../packages/protocol/src/registry.ts';
import { WIRE_VERSION, schemaId } from '../../packages/protocol/src/version.ts';
import { registerStableDefNames } from './schema-defs.ts';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '../..');
const jsonDir = join(repoRoot, 'packages/protocol/schemas');
const generatedDir = join(repoRoot, 'packages/protocol/src/generated');
const generatedFile = join(generatedDir, 'json-schemas.ts');

/** Recursively sort object keys so serialisation is order-independent. */
function sortDeep(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortDeep);
  if (value === null || typeof value !== 'object') return value;
  const entries = Object.entries(value as Record<string, unknown>).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  const out: Record<string, unknown> = {};
  for (const [key, entry] of entries) out[key] = sortDeep(entry);
  return out;
}

function buildSchemas(): Record<string, unknown> {
  registerStableDefNames();
  const out: Record<string, unknown> = {};
  for (const name of PUBLISHED_SCHEMA_NAMES) {
    const schema = PUBLISHED_SCHEMAS[name];
    const generated = z.toJSONSchema(schema, {
      target: 'draft-2020-12',
      // Wire DTOs are what a consumer *receives*, so defaults must be applied
      // and branded strings must appear as plain strings.
      io: 'output',
      // A schema we cannot represent is a contract defect, not something to
      // paper over with `{}`.
      unrepresentable: 'throw',
      cycles: 'ref',
      // Only *registered* sub-schemas become `$defs`; everything else is
      // inlined. `reused: 'ref'` would additionally extract every incidentally
      // repeated node under an auto-numbered `__schemaN` key that renumbers on
      // unrelated edits. Larger output is a fair price for a reviewable diff.
      reused: 'inline',
    }) as Record<string, unknown>;

    const withIdentity = sortDeep({
      ...generated,
      $id: schemaId(name),
      $schema: 'https://json-schema.org/draft/2020-12/schema',
      title: name,
      'x-wire-version': WIRE_VERSION,
    });

    // Guard the property that makes the drift check reviewable: every `$defs`
    // key must be a name someone chose. An auto-numbered `__schemaN` renumbers
    // on unrelated edits and makes diffs unreadable.
    const anonymous = JSON.stringify(withIdentity).match(/__schema\d+/g);
    if (anonymous) {
      throw new Error(
        `schema \`${name}\` emitted anonymous $defs (${[...new Set(anonymous)].sort().join(', ')}). ` +
          'Add the shared sub-schema to NAMED_DEFS in tools/repo/schema-defs.ts.',
      );
    }

    out[name] = withIdentity;
  }
  return out;
}

function renderJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function renderGeneratedModule(schemas: Record<string, unknown>): string {
  const lines: string[] = [];
  lines.push('// GENERATED by tools/repo/generate-schemas.ts — do not edit by hand.');
  lines.push('// Run `pnpm schema:generate` after changing any published Zod schema.');
  lines.push('');
  lines.push(`export const JSON_SCHEMA_WIRE_VERSION = ${JSON.stringify(WIRE_VERSION)};`);
  lines.push('');
  lines.push('export const JSON_SCHEMAS = {');
  for (const name of PUBLISHED_SCHEMA_NAMES) {
    lines.push(`  ${JSON.stringify(name)}: ${JSON.stringify(schemas[name])},`);
  }
  lines.push('} as const satisfies Record<string, unknown>;');
  lines.push('');
  return lines.join('\n');
}

function currentJsonFiles(): Map<string, string> {
  const files = new Map<string, string>();
  if (!existsSync(jsonDir)) return files;
  for (const entry of readdirSync(jsonDir).sort()) {
    if (entry.endsWith('.json')) files.set(entry, readFileSync(join(jsonDir, entry), 'utf8'));
  }
  return files;
}

function main(argv: readonly string[]): number {
  const check = argv.includes('--check');
  const schemas = buildSchemas();

  const expectedJson = new Map<string, string>();
  for (const name of PUBLISHED_SCHEMA_NAMES) {
    expectedJson.set(`${name}.json`, renderJson(schemas[name]));
  }
  const expectedModule = renderGeneratedModule(schemas);

  if (check) {
    const problems: string[] = [];
    const actual = currentJsonFiles();

    for (const [file, content] of expectedJson) {
      const found = actual.get(file);
      if (found === undefined) problems.push(`missing packages/protocol/schemas/${file}`);
      else if (found !== content) problems.push(`stale packages/protocol/schemas/${file}`);
    }
    for (const file of actual.keys()) {
      if (!expectedJson.has(file)) problems.push(`orphaned packages/protocol/schemas/${file}`);
    }

    const moduleOnDisk = existsSync(generatedFile) ? readFileSync(generatedFile, 'utf8') : undefined;
    if (moduleOnDisk === undefined) problems.push('missing packages/protocol/src/generated/json-schemas.ts');
    else if (moduleOnDisk !== expectedModule) problems.push('stale packages/protocol/src/generated/json-schemas.ts');

    // Determinism self-check: a second build must be byte-identical.
    const second = buildSchemas();
    for (const name of PUBLISHED_SCHEMA_NAMES) {
      if (renderJson(second[name]) !== renderJson(schemas[name])) {
        problems.push(`non-deterministic schema emission for \`${name}\``);
      }
    }

    if (problems.length > 0) {
      process.stderr.write(`schema:check: ${problems.length} problem(s)\n`);
      for (const problem of problems) process.stderr.write(`  ${problem}\n`);
      process.stderr.write('  run `pnpm schema:generate` and review the diff\n');
      return 1;
    }
    process.stdout.write(`schema:check: OK — ${PUBLISHED_SCHEMA_NAMES.length} schemas, no drift\n`);
    return 0;
  }

  rmSync(jsonDir, { recursive: true, force: true });
  mkdirSync(jsonDir, { recursive: true });
  for (const [file, content] of expectedJson) {
    writeFileSync(join(jsonDir, file), content, 'utf8');
  }
  mkdirSync(generatedDir, { recursive: true });
  writeFileSync(generatedFile, expectedModule, 'utf8');

  process.stdout.write(
    `schema:generate: wrote ${PUBLISHED_SCHEMA_NAMES.length} schemas to packages/protocol/schemas\n`,
  );
  return 0;
}

process.exit(main(process.argv.slice(2)));
