/**
 * `@relvo-labs/agent-protocol` — the authoritative wire contract.
 *
 * Zod schemas are the source of truth. TypeScript types are inferred from them
 * and JSON Schema is generated from them, so the three can never disagree.
 *
 * Pre-1.0: this contract is explicitly unstable. Negotiate on `WIRE_VERSION`.
 */

export { WIRE_VERSION, WIRE_STABILITY, SCHEMA_ID_BASE, schemaId } from './version.ts';

export {
  type JsonPrimitive,
  type JsonValue,
  type JsonObject,
  JsonPrimitiveSchema,
  JsonValueSchema,
  JsonObjectSchema,
  isJsonValue,
} from './json.ts';

export {
  ID_PREFIX,
  type IdKind,
  SessionIdSchema,
  TurnIdSchema,
  RunIdSchema,
  InteractionIdSchema,
  EventIdSchema,
  WorkspaceLeaseIdSchema,
  CommandIdSchema,
  SequenceSchema,
  CursorSchema,
  TimestampSchema,
  type SessionId,
  type TurnId,
  type RunId,
  type InteractionId,
  type EventId,
  type WorkspaceLeaseId,
  type CommandId,
  type Sequence,
  type Cursor,
  type Timestamp,
  cursorFromSequence,
  sequenceFromCursor,
  type IdFactory,
  type Clock,
  createCounterIdFactory,
  createFixedClock,
  createSystemClock,
} from './ids.ts';

export {
  AgentErrorCodeSchema,
  AgentErrorSchema,
  type AgentErrorCode,
  type AgentError,
  agentError,
  AgentRuntimeError,
  isAgentRuntimeError,
  toAgentError,
} from './errors.ts';

export {
  InterruptModeSchema,
  InterruptCapabilitySchema,
  StreamingCapabilitySchema,
  RunCapabilitySchema,
  ApprovalModeSchema,
  ApprovalCapabilitySchema,
  QuestionCapabilitySchema,
  InteractionCapabilitySchema,
  WorkspaceRequirementSchema,
  WorkspaceCapabilitySchema,
  RecoveryCapabilitySchema,
  ProviderRecoveryRecordSchema,
  ProviderDescriptorSchema,
  type InterruptMode,
  type ApprovalMode,
  type RunCapability,
  type InteractionCapability,
  type WorkspaceCapability,
  type RecoveryCapability,
  type ProviderRecoveryRecord,
  type ProviderDescriptor,
  type ProviderDescriptorInput,
} from './capability.ts';

export {
  SessionStateSchema,
  TurnStateSchema,
  RunStateSchema,
  type SessionState,
  type TurnState,
  type RunState,
  SESSION_TERMINAL_STATES,
  TURN_TERMINAL_STATES,
  RUN_TERMINAL_STATES,
  SESSION_STATE_TABLE,
  TURN_STATE_TABLE,
  RUN_STATE_TABLE,
  SESSION_COMMAND_MATRIX,
  type SessionCommandKind,
  type TransitionTable,
  canTransition,
  isTerminal,
  nextStates,
  isCommandAdmissible,
} from './lifecycle.ts';

export {
  QuestionChoiceSchema,
  QuestionRequestSchema,
  ApprovalSubjectSchema,
  ApprovalRequestSchema,
  InteractionRequestSchema,
  QuestionResponseSchema,
  ApprovalResponseSchema,
  InteractionResponseSchema,
  InteractionStatusSchema,
  SettlementOutcomeSchema,
  InteractionSettlementSchema,
  AgentInteractionSchema,
  type QuestionRequest,
  type ApprovalRequest,
  type InteractionRequest,
  type InteractionKind,
  type QuestionResponse,
  type ApprovalResponse,
  type InteractionResponse,
  type InteractionStatus,
  type SettlementOutcome,
  type InteractionSettlement,
  type AgentInteraction,
  checkResponseAgainstRequest,
} from './interaction.ts';

export {
  WorkspaceOwnershipSchema,
  ExistingWorkspaceSpecSchema,
  ManagedWorkspaceSpecSchema,
  WorkspaceSpecSchema,
  WorkspaceLeaseDescriptorSchema,
  WorkspaceReleaseReportSchema,
  type WorkspaceOwnership,
  type ExistingWorkspaceSpec,
  type ManagedWorkspaceSpec,
  type WorkspaceSpec,
  type WorkspaceLeaseDescriptor,
  type WorkspaceReleaseReport,
  ownershipFor,
} from './workspace.ts';

export {
  TextPartSchema,
  FileRefPartSchema,
  TurnInputPartSchema,
  TurnInputSchema,
  UsageSchema,
  RunTerminationSchema,
  AgentRunSchema,
  AgentTurnSchema,
  AgentSessionSchema,
  SessionSnapshotSchema,
  type TurnInputPart,
  type TurnInput,
  type Usage,
  type RunTermination,
  type AgentRun,
  type AgentTurn,
  type AgentSession,
  type SessionSnapshot,
} from './entities.ts';

export {
  EventPayloadSchema,
  ProviderEventPayloadSchema,
  EventEnvelopeSchema,
  ProviderEventInputSchema,
  PROVIDER_EMITTABLE_EVENT_TYPES,
  type EventPayload,
  type EventType,
  type ProviderEventPayload,
  type EventEnvelope,
  type ProviderEventInput,
  isEventOfType,
} from './events.ts';

export {
  OpenSessionCommandSchema,
  SubmitTurnCommandSchema,
  InterruptRunCommandSchema,
  RespondToInteractionCommandSchema,
  CloseSessionCommandSchema,
  AgentCommandSchema,
  SessionOpenedResultSchema,
  TurnAcceptedResultSchema,
  RunInterruptRequestedResultSchema,
  InteractionSettledResultSchema,
  SessionClosedResultSchema,
  CommandResultSchema,
  CommandDispositionSchema,
  CommandReceiptSchema,
  type OpenSessionCommand,
  type SubmitTurnCommand,
  type InterruptRunCommand,
  type RespondToInteractionCommand,
  type CloseSessionCommand,
  type AgentCommand,
  type CommandType,
  type OpenSessionCommandInput,
  type SubmitTurnCommandInput,
  type InterruptRunCommandInput,
  type RespondToInteractionCommandInput,
  type CloseSessionCommandInput,
  type AgentCommandInput,
  type CommandResult,
  type CommandResultFor,
  type CommandDisposition,
  type CommandReceipt,
  canonicalCommandFingerprint,
} from './commands.ts';

export {
  OverflowPolicySchema,
  SubscriptionRequestSchema,
  SubscriptionMessageSchema,
  EventPageSchema,
  RunFilterSchema,
  type OverflowPolicy,
  type SubscriptionRequest,
  type SubscriptionRequestInput,
  type SubscriptionMessage,
  type EventMessage,
  type CaughtUpMessage,
  type OverflowMessage,
  type ClosedMessage,
  type EventPage,
  type RunFilter,
  isEventMessage,
  isEventMessageOfType,
} from './subscription.ts';

export { PUBLISHED_SCHEMAS, PUBLISHED_SCHEMA_NAMES, type PublishedSchemaName } from './registry.ts';
