#!/usr/bin/env node
/**
 * Deterministic generator for `.agents/skills/INDEX.md`.
 *
 * Output depends only on the SKILL.md files on disk: skills are sorted by name,
 * ownership tokens and relations are sorted, and nothing time- or
 * environment-dependent is emitted. `--check` fails if the committed index does
 * not byte-match a fresh render, so a renamed or re-scoped skill cannot ship
 * with a stale index.
 *
 * Usage:
 *   node tools/skills/generate-index.ts [--check] [--root <repoRoot>] [--skill-root <rel>]
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import { CANONICAL_SKILL_ROOT, scanSkillRoot, type SkillDoc } from './lib/model.ts';

const BANNER = '<!-- GENERATED by tools/skills/generate-index.ts — do not edit by hand. -->';

function sortedTokens(entries: readonly { token: string }[]): string[] {
  return entries
    .map((entry) => entry.token)
    .filter((token) => token !== '')
    .sort();
}

function renderSkill(skill: SkillDoc): string {
  const name = skill.name ?? skill.dirName;
  const lines: string[] = [];

  lines.push(`### \`${name}\``);
  lines.push('');
  lines.push(`- **Version:** ${skill.version ?? 'unknown'} (${skill.stability ?? 'unknown'})`);
  lines.push(`- **Path:** \`${skill.relPath}\``);
  lines.push(`- **Description:** ${skill.description ?? ''}`);

  const tags = [...(skill.tags ?? [])].sort();
  if (tags.length > 0) {
    lines.push(`- **Tags:** ${tags.map((tag) => `\`${tag}\``).join(', ')}`);
  }

  const owns = sortedTokens(skill.owns);
  if (owns.length > 0) {
    lines.push(`- **Owns:** ${owns.map((token) => `\`${token}\``).join(', ')}`);
  }

  const relations = skill.relations
    .filter((relation) => relation.verb !== '' && relation.target !== '')
    .map((relation) => `\`${relation.verb}\` → \`${relation.target}\``)
    .sort();
  if (relations.length > 0) {
    lines.push(`- **Relationships:** ${relations.join(', ')}`);
  }

  lines.push('');
  return lines.join('\n');
}

export function renderIndex(skills: readonly SkillDoc[], skillRoot: string): string {
  const ordered = [...skills].sort((a, b) => {
    const an = a.name ?? a.dirName;
    const bn = b.name ?? b.dirName;
    return an < bn ? -1 : an > bn ? 1 : 0;
  });

  const lines: string[] = [];
  lines.push(BANNER);
  lines.push('');
  lines.push('# Local skill index');
  lines.push('');
  lines.push(
    `\`${skillRoot}\` is the only skill root in this repository. See \`AGENTS.md\` for the read-before-write rule.`,
  );
  lines.push('');
  lines.push(`Regenerate with \`pnpm skills:index\`. Verify with \`pnpm skills:check\`.`);
  lines.push('');
  lines.push('## Ownership map');
  lines.push('');
  lines.push('| Owned surface | Skill |');
  lines.push('| --- | --- |');

  const ownership: { token: string; owner: string }[] = [];
  for (const skill of ordered) {
    for (const token of sortedTokens(skill.owns)) {
      ownership.push({ token, owner: skill.name ?? skill.dirName });
    }
  }
  ownership.sort((a, b) => (a.token < b.token ? -1 : a.token > b.token ? 1 : a.owner < b.owner ? -1 : 1));
  for (const row of ownership) {
    lines.push(`| \`${row.token}\` | \`${row.owner}\` |`);
  }

  lines.push('');
  lines.push('## Skills');
  lines.push('');
  for (const skill of ordered) {
    lines.push(renderSkill(skill));
  }

  return `${lines
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trimEnd()}\n`;
}

function main(argv: readonly string[]): number {
  const here = dirname(fileURLToPath(import.meta.url));
  const defaultRepoRoot = resolve(here, '../..');

  const rootIndex = argv.indexOf('--root');
  const skillRootIndex = argv.indexOf('--skill-root');
  const repoRoot = rootIndex === -1 ? defaultRepoRoot : resolve(argv[rootIndex + 1]!);
  const skillRoot = skillRootIndex === -1 ? CANONICAL_SKILL_ROOT : argv[skillRootIndex + 1]!;

  const { skills } = scanSkillRoot(repoRoot, skillRoot);
  const rendered = renderIndex(skills, skillRoot);
  const target = join(repoRoot, skillRoot, 'INDEX.md');

  if (argv.includes('--check')) {
    if (!existsSync(target)) {
      process.stderr.write(`skills:index: ${skillRoot}/INDEX.md is missing; run \`pnpm skills:index\`\n`);
      return 1;
    }
    const current = readFileSync(target, 'utf8');
    if (current !== rendered) {
      process.stderr.write(`skills:index: ${skillRoot}/INDEX.md is stale; run \`pnpm skills:index\`\n`);
      return 1;
    }
    process.stdout.write(`skills:index: OK — ${skills.length} skills, index up to date\n`);
    return 0;
  }

  writeFileSync(target, rendered, 'utf8');
  process.stdout.write(`skills:index: wrote ${skillRoot}/INDEX.md (${skills.length} skills)\n`);
  return 0;
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  process.exit(main(process.argv.slice(2)));
}
